labppw/urls.py
from django.contrib import admin
from django.urls import include, path
from story1.views import storysatu
from story7.views import storytujuh

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('story3.urls')),
    path('story1', storysatu),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('story7', storytujuh),
    path('buku/', include('story8.urls')),
    path('', include('story9.urls')),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='home'),
    path('photos', views.photos, name='photos')
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('isijadwal/', views.inputform, name='addform'),
    path('jadwal/', views.showform, name='showform'),
    path('saveform/', views.saveform, name='saveform'),
    path('jadwal/<id>/delete', views.deleteform ),
    path('jadwal/details/<id>', views.detailform ),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('acara/', views.index, name='index'),
    path('acara/<id>/deleteacara', views.deleteAcara ),
    path('acara/<id>/deletepeserta', views.deletePeserta ),
]

story8/urls.py
from django.urls import path

from story8.views import story8_url, story8_data

app_name = 'story8'

urlpatterns = [
    path('', story8_url, name='index'),
    path('data', story8_data, name='data'),
]

story3/models.py
from django.db import models

# Create your models here.

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home.html')

def photos(request):
    return render(request, 'gallery.html')

story3/templates/gallery.html
{% extends 'index.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock meta %}

{% block style %}
<style>
    .sosmed {
        padding-top: 30px;
    }

    .sosmed a {
        padding: 0 10px;
        color: #F3C89D;
    }

    .sosmed a:hover {
        color: #F2F2F2;
    }

    .boxes {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
    }

    #cover2 {
        background-image: url("static/img/texture.gif");
        background-size: cover;
        background-attachment: fixed;
        height: 100vh;
        text-align: center;
    }

    #cover2 h1 {
        text-align: center;
        color: #FAFAFA;
        font-size: 64px;
    }

    #gallery {
        background-image: linear-gradient(#020300, #1A1916);
    }

    #gallery .box {
        width: 20%;
        height: 80vh;
        padding: 100px 10px 0 10px;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #F2F2F2;
    }

    #gallery .box p {
        width: 60%;
    }

    #gallery img {
        transform: rotate(-6deg);
        transition: 200ms;
    }

    #gallery img:hover {
        transform: rotate(0deg);
    }

    .last {
        margin-bottom: 100px;
    }

@media only screen and (max-width: 800px) {
    #cover2 h1 {
        font-size: 32pt;
    }
    
    #gallery .boxes {
        margin-top: 100px;
        margin-bottom: 100px;
    }

    #gallery .box {
        width: 100%;
        height: auto;
        text-align: center;
    }

    #gallery img {
        transform: rotate(0deg);
        transition: 0ms;
    }

    .last {
        margin-bottom: 0;
    }
}
</style>
{% endblock style %}

{% block content %}
{% include 'navbar.html' %}
<div id="cover2">
    <div class="container">
        <div class="center">
            <h1>aquí,<br>imágenes</h1>
            <div class="sosmed">
                <a href="http://instagram.com/natsyz" target="_blank"><i class="fab fa-instagram"></i></a>
                <a href="http://twitter.com/napnath" target="_blank"><i class="fab fa-twitter"></i></a>
                <a href="https://www.linkedin.com/in/natasya-zahra-261756199/" target="_blank"><i class="fab fa-linkedin-in"></i></a>              
            </div>
        </div>
    </div>
</div>
<div id="gallery">
    <div class="container">
        <div class="boxes center">
            <div class="box">
                <img src="{% static 'img/photo01.png' %}" alt="">
            </div>
            <div class="box">
                <h1>01</h1><br>
                <p class="hlight">Junior High is probably the best moment that i’ve ever had.</p>
                <br>
                <p>Here, me with the very lovely person i’ve ever know. My bestfriend, and my crush (still).</p>
            </div>
        </div>
        <div class="boxes">
            <div class="box">
                <img src="{% static 'img/photo02.png' %}" alt="">
            </div>
            <div class="box">
                <h1>02</h1><br>
                <p class="hlight">Shot inside public mini bus (angkot) on my way home from highschool.</p>
                <br>
                <p>Stress.</p>
            </div>
        </div>
        <div class="boxes">
            <div class="box">
                <img src="{% static 'img/photo03.png' %}" alt="">
            </div>
            <div class="box last">
                <h1>03</h1><br>
                <p class="hlight">An event, a good one. The trees was nice.</p>
                <br>
                <p>Hopefully i could go here really soon.</p>
                <button type="button" onclick="location.href='#cover2'" class="btn btn-dark btn-sm" href="#cover2">
                    up
                </button>
                <br>
            </div>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock content %}

story3/templates/home.html
{% extends 'index.html' %}
{% load static %}

{% block meta %}
<title>Nat Story</title>
{% endblock meta %}

{% block style %}
<style>
  #cover {
    background-image: url("static/img/cover.png");
    background-size: cover;
    background-attachment: fixed;
    height: 100vh;
  }

  #cover1 {
    background-image: url("static/img/cover2.jpg");
    background-size: cover;
    background-attachment: fixed;
    height: 50vh;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow-x: hidden;
    overflow-y: hidden;
  }

  .half-circle {
    position: absolute;
    width: 200px;
    height: 200px;
    border: 18px solid #FAFAFA;
    /* border-radius: 50%; */
    /* right: ; */
    /* bottom: -100px; */
    /* background-color: #FAFAFA; */
    
  }

  #cover h1 {
    color: #FAFAFA;
    font-size: 64px;
  }

  .sosmed {
    padding-top: 30px;
  }

  .sosmed a {
    padding: 0 10px;
    color: #F3C89D;
  }

  .sosmed a:hover {
    color: #F2F2F2;
  }


  #about {
    /* height: 100vh; */
    /* padding-bottom: 20px; */
    background-color: #FAFAFA;
    overflow-x: hidden;
  }

  .title {
    height: 160px;
    padding-top: 100px;
    text-align: center;
  }

  .title h1 {
    font-size: 24px;
    margin-bottom: 5px;
  }

  .content {
    /* height: calc(100% - 160px); */
  }

  .content h1 {
    font-size: 18px;
    padding-bottom: 30px;
  }

  .box {
    padding: 100px 10px 0 10px;
    width: 30%;
  }

  .one {
    text-align: right;
  }

  .two {
    text-align: center;
  }

  .two img {
    width: 200px;
    border-radius: 50%;
    margin-bottom: 20px;
  }

  td {
    padding-right: 40px;
  }


  #resume {
    /* height: 100vh; */
    padding-bottom: 120px;
    background-color: #FAFAFA;
  }

  #resume .box {
    padding: 0 60px;
    margin-top: 100px;
  }

  #resume .one {
    border-right: 2px solid #1A1916;
  }

  #resume .gambar {
    width: 20%;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  #portfolio {
    overflow-x: hidden;
    padding-bottom: 80px;
    background-color: #1A1916;
  }

  #portfolio .title {
    color: #FAFAFA;
  }

  #portfolio .box {
    text-align: center;
  }

  #story {
    overflow-x: hidden;
    padding-bottom: 120px;
    background-color: #1A1916;
  }

  #story .title {
    color: #FAFAFA;
  }

  #story .box {
    text-align: center;
  }

  #story img {
    border: 2px solid #FAFAFA;
  }

  .img-warp {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .img-desc {
    position: absolute;
    bottom: 20px;
    left: 0;
    right: 0;
    background: rgb(26, 25, 22, 0.80);
    color: #FAFAFA;
    visibility: hidden;
    opacity: 0;
    transition: opacity .2s, visibility .2s;
  }

  .img-warp:hover .img-desc {
    visibility: visible;
    opacity: 1;
  }

  .img-hover{
    position: absolute;
    width: 300px;
    background: #FAFAFA;
    bottom: 5px;
    color: #FAFAFA;
    visibility: hidden;
    opacity: 0;
    transition: opacity .2s, visibility .2s;
  }
  .img-warp:hover .img-hover {
    visibility: visible;
    opacity: 1;
  }

@media only screen and (max-width: 800px) {
  .box {
      width: 100%;
      padding: 0;
      padding-bottom: 20px;
  }
  #cover{
      background-image: url("static/img/cover3.jpg");
      text-align: center;
  }

  #cover h1 {
      font-size: 32pt;
  }

  #about {
    height: auto;
  }

  #resume, #portfolio, #story {
      height: auto;
      padding-bottom: 50px;
  }

  #about .two {
    padding-top: 30px;
  }

  .content {
      height: auto;
  }

  .title {
      padding-top: 50px;
      margin: 0;
  }

  .title h1 {
      font-size: 16px;
  }

  .title p {
      border-bottom: 1px solid #1A1916;
      padding-bottom: 20px;
  }
  
  .one, .three h1 {
      text-align: center;
  }

  table {
      padding-left: 10px;
  }

  #resume .one {
      border: 0;
  }
  
  #resume .box {
      text-align: center;
      margin: 0;
      padding: 0;
      padding-bottom: 50px;
  }
  
  #resume .gambar {
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
  }

  #portfolio, #story {
      background-image: url("{{ STATIC_URL }}main/static/img/texture.gif");
  }

  #portfolio .title p, #story .title p {
      border-bottom: 1px solid #F2F2F2;
  }

  #portfolio img, #story img {
      max-width: 100%;
      height: auto;
  }
  .img-desc {
      display: none;
  }
}

</style>
{% endblock style %}

{% block content %}
{% include 'navbar.html' %}
  <div id="cover">
      <div class="container">
          <div class="center">
              <h1>soy,<br>natasya</h1>
              <div class="sosmed">
                  <a href="http://instagram.com/natsyz" target="_blank"><i class="fab fa-instagram"></i></a>
                  <a href="http://twitter.com/napnath" target="_blank"><i class="fab fa-twitter"></i></a>
                  <a href="https://www.linkedin.com/in/natasya-zahra-261756199/" target="_blank"><i class="fab fa-linkedin-in"></i></a>              
              </div>
          </div>
      </div>
  </div>
  <div id="about">
      <div class="container">
          <div class="title">
              <h1>ABOUT ME</h1>
              <p>LET ME INTRODUCE MYSELF</p>
          </div>
          <div class="content">
              <div class="boxes center">
                  <div class="box one">
                      <h1 class="hide">A BIT ABOUT ME</h1>
                      <!-- <p class="hlight">I am very passionate on education and digital design</p> -->
                      <p class="hlight">Highly motivated university student who passionate to learn more about web development.</p>
                      <br>
                      <!-- <p>I like to distract myself by seeing other people's life on YouTube and sometimes draw a thing. Let's be friend! :)</p> -->
                      <p>I am also interested in graphic design, video editing, and sharing my knowledge to others.</p>
                      <div class="sosmed">
                          <a href="http://instagram.com/natsyz" target="_blank"><i class="fab fa-instagram hlight"></i></a>
                          <a href="http://twitter.com/napnath" target="_blank"><i class="fab fa-twitter hlight"></i></a>
                          <a href="https://www.linkedin.com/in/natasya-zahra-261756199/" target="_blank"><i class="fab fa-linkedin-in hlight"></i></a>              
                      </div>
                  </div>
                  <div class="box two">
                      <img src="{% static 'img/pict.jpg' %}" alt="">
                  </div>
                  <div class="box three hide">
                      <h1>PROFILE</h1>
                      <table>
                          <tr>
                              <td class="hlight">Name</td>
                              <td>Natasya Zahra</td>
                          </tr>
                          <tr>
                              <td class="hlight">Major</td>
                              <td>Computer Science</td>
                          </tr>
                          <tr>
                              <td class="hlight">University</td>
                              <td>Universitas Indonesia</td>
                          </tr>
                          <tr>
                              <td class="hlight">Email</td>
                              <td>whynatasya@gmail.com</td>
                          </tr>
                      </table>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- <div id="cover1">
    <div class="half-circle">
    </div>
  </div> -->
  <div id="resume">
      <div class="container">
          <div class="title">
              <h1>RESUME</h1>
              <p>KNOW MORE ABOUT MY PAST</p>
          </div>
          <div class="content">
              <div class="boxes">
                  <div class="gambar">
                      <img src="{% static 'img/briefcase.png' %}" class="hide" alt="">
                  </div>
                  <div class="box one">
                      <h1>EXPERIENCE</h1>
                      <p class="hlight">BKUI 20</b>
                      <p>Staff of Graphic Design</p>
                      <br>
                      <p class="hlight">COMPFEST 12</p>
                      <p>Staff of Visual Design</p>
                      <br>
                      <p class="hlight">PMB Fasilkom UI 2020</p>
                      <p>Staff of Academic</p>
                      <br>
                      <p class="hlight">BETIS Fasilkom UI 2020</p>
                      <p>Staff of Mentor</p>
                  </div>
                  <div class="box">
                      <h1>EDUCATION</h1>
                      <p class="hlight">2019 - Present</b>
                      <p>Universitas Indonesia</p>
                      <br>
                      <p class="hlight">2017 - 2019</p>
                      <p>SMAN 2 Tangerang Selatan</p>
                      <br>
                      <p class="hlight">2014 - 2017</p>
                      <p>SMPN 1 Tangerang Selatan</p>
                      <br>
                      <p class="hlight">2008 - 2014</p>
                      <p>SDN 3 Jelupang</p>
                  </div>
                  <div class="gambar">
                      <img src="{% static 'img/book.png' %}"x alt="">
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div id="portfolio">
      <div class="container">
          <div class="title">
              <h1>DRAWING</h1>
              <p>MY LATEST DRAWING PROJECT</p>
          </div>
          <div class="content">
              <div class="boxes">
                  <div class="box">
                      <div class="img-warp">
                          <a href="https://www.instagram.com/p/Bo6fFpzn9ej/" target="_blank"><img src="{% static 'img/pict1.png' %}" alt=""></a>
                          <p class="img-desc">Holand - Watercolor</p>
                      </div>
                  </div>
                  <div class="box">
                      <div class="img-warp">
                          <a href="https://www.instagram.com/p/BxaWn3WF8T_/" target="_blank"><img src="{% static 'img/pict2.png' %}" alt=""></a>
                          <p class="img-desc">TAFT F50- Watercolor</p>
                      </div>
                  </div>
                  <div class="box">
                      <div class="img-warp">
                          <a href="https://www.instagram.com/p/BzFQfqHFRxc/" target="_blank"><img src="{% static 'img/pict3.png' %}" alt=""></a>
                          <p class="img-desc">C Evans - Sketch</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div id="story">
    <div class="container">
      <div class="title">
          <h1>STORY</h1>
          <p>THIS SITE'S OTHER PAGES</p>
      </div>
      <div class="content">
        <div class="boxes">
          <div class="box">
            <div class="img-warp">
                <a href="{% url 'story3:photos' %}"><img src="{% static 'img/sgallery.png' %}" alt=""></a>
                <p class="img-hover">.</p>
            </div>
          </div>
          <div class="box">
            <div class="img-warp">
                <a href="{% url 'story6:index' %}"><img src="{% static 'img/sagenda.png' %}" alt=""></a>
                <p class="img-hover">.</p>
            </div>
          </div>
          <div class="box">
            <div class="img-warp">
                <a href="{% url 'story5:showform' %}"><img src="{% static 'img/sschedule.png' %}" alt=""></a>
                <p class="img-hover">.</p>
            </div>
          </div>
          <div class="box">
            <div class="img-warp">
                <a href="{% url 'story8:index' %}"><img src="{% static 'img/sbook.png' %}" alt=""></a>
                <p class="img-hover">.</p>
            </div>
          </div>
          <div class="box">
            <div class="img-warp">
                <a href="/story7"><img src="{% static 'img/saccordion.png' %}" alt=""></a>
                <p class="img-hover">.</p>
            </div>
          </div>
          <div class="box">
            <div class="img-warp">
                <a href="/story1"><img src="{% static 'img/ssimple.png' %}" alt=""></a>
                <p class="img-hover">.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% include 'footer.html' %}
{% endblock content %}