labppw/urls.py
from django.contrib import admin
from django.urls import include, path
from story1.views import storysatu
from story7.views import storytujuh

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('story3.urls')),
    path('story1', storysatu),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('story7', storytujuh),
    path('buku/', include('story8.urls')),
    path('', include('story9.urls')),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('isijadwal/', views.inputform, name='addform'),
    path('jadwal/', views.showform, name='showform'),
    path('saveform/', views.saveform, name='saveform'),
    path('jadwal/<id>/delete', views.deleteform ),
    path('jadwal/details/<id>', views.detailform ),
]

story5/models.py
from django.db import models

# Create your models here.

class Form(models.Model):
    nama_mata_kuliah = models.CharField(max_length=50)
    dosen_pengajar = models.CharField(max_length=50)
    jumlah_sks = models.CharField(max_length=2)
    deskripsi_mata_kuliah = models.CharField(max_length=200)
    tahun_ajar = models.CharField(max_length=20)
    ruang_kelas = models.CharField(max_length=20)

    def __str__(self):
        return self.nama_mata_kuliah

story5/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .formulir import Input_Form
from .models import Form

# Create your views here.
def inputform(request):
    response = {
        'input_form' : Input_Form,
    }
    return render(request, 'form.html', response)

def showform(request):
    response = {
        'form_table' : Form.objects.all(),
    }
    return render(request, 'jadwal.html', response)

def saveform(request):
    # form = Input_Form(request.POST or None)
    # return HttpResponseRedirect('/');
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method =='POST'):
        form.save()
        print("saved")
        return HttpResponseRedirect('/isijadwal')
    else:
        return HttpResponseRedirect('/isijadwal')

def deleteform(request, id): 
    obj = get_object_or_404(Form, id = id) 
    obj.delete() 
    return HttpResponseRedirect("/jadwal")

def detailform(request, id):
    response = {
        'item' : get_object_or_404(Form, id = id),
    }
    return render(request, 'fulldesc.html', response)

story5/templates/form.html
{% extends 'index.html' %}
{% load static %}

{% block meta %}
<title>Add Schedule</title>
{% endblock meta %}

{% block style %}
<style>

.jadwal{
  background-image: url("https://i.ibb.co/Lv7Qw65/Group-2.png");
  background-size: cover;
  background-attachment: fixed;
  padding-top: 20px;
  padding-bottom: 40px;
}

.container2 {
  max-width: 900px;
  padding: 0 30px;
  margin: 0 auto;
  height: 100%;
}

#cover {
  height: 200px;
  margin-bottom: 20px;
  color:white;
}

#cover h1 {
  text-align: center;
}

.bgblack{
  background-image: url("https://cutewallpaper.org/21/black-background-gif/Pin-on-Super-gif.gif");
  background-size: cover;
  background-attachment: fixed;
  border-radius: 20px;
}

.bgwhite {
  background-color:white;
  border: 5px solid black;
  border-radius: 20px;
}

.title {
  text-align: center;
  margin: 60px 0;
}

.title h1 {
  font-size: 24px;
  margin-bottom: 5px;
}

form{
  width: 80%;
  margin: 0 auto;
  padding: 60px 0;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  float: right;
  min-width: 100px;
  background-color: #22211d;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #c96400;
}

.button {
  position: fixed;
  bottom: 35px;
  right: 35px;
  background-color:  #111111;
  border: none;
  color: white;
  padding: 15px 17px;
  text-decoration: none;
  font-size: 24px;
  border-radius: 50%;
}

.button:hover{
  background-color: #FC7E00;
}


@media only screen and (max-width: 800px) {
.jadwal{
  background-image: url("https://cutewallpaper.org/21/black-background-gif/Pin-on-Super-gif.gif");
}

.bgwhite {
  margin: 0 30px;
  font-size: 14px;
}

#cover {
  height: 100px;
}
.title h1 {
  font-size: 18px;
}
form{
  width: 100%;
}
}
</style>
{% endblock style %}


{% block content %}
{% include 'navbar.html' %}

<div class="jadwal">
  <div id="cover">
    <div class="container2 bgblack">
      <div class="title center">
        <h1>ADD SCHEDULE</h1>
        <p>FILL THE FORM BELOW</p>
      </div>
    </div>
  </div>
  <a href="{% url 'story5:showform' %}" class="button"><i class="fas fa-table"></i></a>
  <div id="form">
      <div class="container2 center bgwhite">
          {% if user.is_authenticated %}

          <form method="POST" action="/saveform/">
            {% csrf_token %}
            {{ input_form }}
            <input class="btn" type="submit" value="tambah">
          </form>

          {% else %}
          <img src="https://i.pinimg.com/originals/eb/17/d0/eb17d0925c49ef13af6e84cdfeaad079.gif" alt="">
          {% endif %}
      </div>
  </div>
</div>

{% include 'footer.html' %}
{% endblock content %}

story5/templates/fulldesc.html
{% extends 'index.html' %}
{% load static %}

{% block meta %}
<title>Nat Story</title>
{% endblock meta %}

{% block style %}
<style>

.details {
    height: calc(100vh - 53px);
    overflow: hidden;
}
.container2 {
    max-width: 1050px;
    padding: 0 30px;
    margin: 0 auto;
}
.tittle {
    width: 100%;
    text-align: center;
    padding: 100px 0 40px 0;
}
.tittle h1 {
    font-size: 24px;
    margin-bottom: 5px;
}
.title h1{
    font-size: 32px;
    color: #1A1916;
    margin-bottom: 15px;
}

.details p{
    padding-bottom: 15px;
}

.hlight{
    font-size: 18px;
}


@media only screen and (max-width: 800px) {
.details {
    min-height: 100vh;
    padding: 100px 20px 50px 20px;
    display: flex;
    flex-direction: column;
    justify-content: center;
}
.tittle{
    display: none;
}
.title h1{
    font-size: 20px;
    margin-bottom: 30px;
}
.hlight{
    font-size: 14px;
    padding-bottom: 5px;
}
}

</style>
{% endblock style %}

{% block content %}
{% include 'navbar.html' %}
<div class="details">
    <div class="container2">
        {% if user.is_authenticated %}
        <div class="tittle center">
            <h1>DETAILS</h1>
            <p>LET'S HAVE A LOOK</p>
        </div>

        <div class="title">
            <h1>{{ item.nama_mata_kuliah }}</h1>
        </div>

        <h1 class="hlight">Dosen Pengajar</h1>
        <p>{{ item.dosen_pengajar }}</p>

        <h1 class="hlight">Jumlah SKS</h1>
        <p>{{ item.jumlah_sks }}</p>

        <h1 class="hlight">Deskripsi</h1>
        <p>{{ item.deskripsi_mata_kuliah }}</p>

        <h1 class="hlight">Tahun Ajar</h1>
        <p>{{ item.tahun_ajar }}</p>

        <h1 class="hlight">Ruang Kelas</h1>
        <p>{{ item.ruang_kelas }}</p>

        {% else %}
        <h1>PLEASE LOGIN TO ACCESS</h1>
        <img src="https://i.pinimg.com/originals/eb/17/d0/eb17d0925c49ef13af6e84cdfeaad079.gif" alt="">
        {% endif %}
    </div>
</div>
{% include 'footer.html' %}
{% endblock content %}

story5/templates/jadwal.html
{% extends 'index.html' %}
{% load static %}

{% block meta %}
<title>Nat Schedule</title>
{% endblock meta %}

{% block style %}
<style>

.container2 {
  max-width: 1050px;
  padding: 0 30px;
  margin: 0 auto;
  height: 100%;
}

#cover {
  text-align: center;
  background-image: url("https://i.ibb.co/Lv7Qw65/Group-2.png");
  background-size: cover;
  background-attachment: fixed;
  height: 100vh;
}

#cover h1 {
  text-align: center;
  color: #1A1916;
  font-size: 64px;
}

.sosmed {
  padding-top: 20px;
}

.sosmed a {
  padding: 0 10px;
  font-size: 24px;
  color: black;
}

.sosmed a:hover {
  color: #FC7E00;
}

.tittle {
  width: 100%;
  text-align: center;
  margin: 60px 0;
}

.tittle h1 {
  font-size: 24px;
  margin-bottom: 5px;
}

.title{
    display: flex;
    justify-content: space-between;
}

.title a{
  font-size: 24px;
  color: #1A1916;
  text-decoration: none;
}

.title a:hover{
  color: #FC7E00;
}

.boxes{
  margin-bottom: 100px;
}

.box a{
  display: contents;
}

.box {
  margin: 15px;
  padding: 20px;
  width: 25%;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.box:hover{
  border: 1px solid #1a1916;
}

.box h1 {
  font-size: 18px;
  padding-bottom: 15px;
  overflow: hidden;
}

.button {
  position: fixed;
  bottom: 35px;
  right: 35px;
  background-color:  #111111;
  border: none;
  color: white;
  padding: 15px 20px;
  text-decoration: none;
  font-size: 24px;
  border-radius: 50%;
}

.button:hover{
  background-color: #FC7E00;
}

.kosonk{
  width: 100%;
  height: calc(100vh - 148px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.kosonk h1{
  text-align: center;
  margin-top: 80px;
  margin-bottom: 30px;
}
.kosonk img{
  width: 200px;
}

@media only screen and (max-width: 800px) {
#cover h1 {
  padding: 0 20px;
  font-size: 32px;
}
.box {
  width: 100%;
}
.title a{
  font-size: 18px;
}
.title h1{
  font-size: 14px;
}
.tittle h1{
  font-size: 18px;
}
.kosonk h1{
  padding: 0 50px;
  font-size: 18px;
}
.kosonk img{
  width: 150px;
}
}

</style>
{% endblock style %}

{% block content %}
{% include 'navbar.html' %}
<div id="cover">
  <div class="container2">
    <div class="center">
        <h1>mira mi horario aquí</h1>
        <div class="sosmed">
          <a href="http://instagram.com/natsyz" target="_blank"><i class="fab fa-instagram"></i></a>
          <a href="http://twitter.com/napnath" target="_blank"><i class="fab fa-twitter"></i></a>
          <a href="https://www.linkedin.com/in/natasya-zahra-261756199/" target="_blank"><i class="fab fa-linkedin-in"></i></a>              
        </div>
    </div>
</div>
</div>
<a href="{% url 'story5:addform' %}" class="button"><i class="fas fa-plus"></i></i></a>
<div id="form-table">
  <div class="container2">
    <div class="boxes">
      {% if user.is_authenticated %}
      {% if form_table %}
      <div class="tittle center">
        <h1>SCHEDULE</h1>
        <p>AM I BUSY? YES I AM</p>
      </div>
      {% for item in form_table %}
      
      <div class="box" onclick="location.href='details/{{ item.id }}';">
        <div class="title">
            <h1>{{ item.nama_mata_kuliah }}</h1>
            <a href="{{ item.id }}/delete"><i class="fas fa-trash-alt"></i></a>
        </div>
        <table>
          <tr>
            <td class="hlight">{{ item.tahun_ajar }}</td>
          </tr>
        </table>   
      </div>
      {% endfor %}
      {% else %}
      <div class="kosonk center">
        <h1>IT SEEMS YOU CAN RELAX A LIL BIT!</h1>
        <img src="https://media3.giphy.com/media/3o7WIx7urV838kHFzW/source.gif" alt="">
      </div>
      {% endif %}
      {% else %}
      <div class="kosonk center">
        <h1>PLEASE LOGIN TO ACCESS</h1>
        <img src="https://i.pinimg.com/originals/eb/17/d0/eb17d0925c49ef13af6e84cdfeaad079.gif" alt="">
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% include 'footer.html' %}
{% endblock content %}